ALTER TABLE `posts` ADD `anonymous` BOOLEAN NOT NULL DEFAULT FALSE AFTER `pinned`;
ALTER TABLE `videos` ADD `anonymous` BOOLEAN NOT NULL DEFAULT FALSE AFTER `unlisted`;
ALTER TABLE `photos` ADD `anonymous` BOOLEAN NOT NULL DEFAULT FALSE AFTER `hash`;
ALTER TABLE `comments` ADD `anonymous` BOOLEAN NOT NULL DEFAULT FALSE AFTER `ad`;
ALTER TABLE `notes` ADD `anonymous` BOOLEAN NOT NULL DEFAULT FALSE AFTER `cached_content`;
