CREATE TABLE `blacklists` (
  `index` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author` BIGINT UNSIGNED NOT NULL,
  `target` BIGINT UNSIGNED NOT NULL,
  `created` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`index`)
) ENGINE = InnoDB;
