version: '3.1'

services:
  db:
    build: .
    restart: always
    privileged: true
    ports:
      - 8888:80

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 7777:8080
