#!/usr/bin/env php
<?php declare(strict_types=1);
namespace openvk;
use Symfony\Component\Console\Application;

$_SERVER["HTTP_ACCEPT_LANGUAGE"] = false;
$bootstrap = require(__DIR__ . "/../../../chandler/Bootstrap.php");
$bootstrap->ignite(true);

$application = new Application();
$application->add(new CLI\RebuildImagesCommand);
$application->add(new CLI\FetchToncoinTransactions);

$application->run();