#!/bin/tcsh

##########################################################################################################\
#         OpenVK AutoInstallation Script for FreeBSD 15         #               /(        )`               #
# ------------------------------------------------------------- #               \ \___   / |               #
#                                                               #               /- _  `-/  '               #
# This script installs OpenVK on an empty FreeBSD 15 box/jail.  #              (/\/ \ \   /\               #
# Copyright (c) 2026 OpenVK contributors                        #              / /   | `    \              #
# ------------------------------------------------------------- #              O O   ) /    |              #
#                                                               #              `-^--'`<     '              #
# This scropt is free software; you can redistribute it and/or  #             (_.)  _  )   /               #
# modify it under the terms of the GNU Lesser General Public    #              `.___/`    /                #
# License as published by the Free Software Foundation; ver 2.1 #                `-----' /                 #
#                                                               #   <----.     __ / __   \                 #
# This script is distributed in the hope that it will be        #  <----|====O)))==) \) /====|             #
# useful, but WITHOUT ANY WARRANTY; without even the implied    #   <----'    `--' `.__,' \                #
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR       #                |        |                #
# PURPOSE. See the GNU Lesser General Public License for more   #                 \       /       /\       #
# details.                                                      #            ______( (_  / \______/        #
###########################################################################################################/

# Verify compatability
command -v freebsd-version
if ($? == 1) then
    echo "Fatal Error: This installation script is for FreeBSD only."
    exit 200
endif

set osVer = `freebsd-version -r`
if ($osVer !~ "15.*") then
    echo "Fatal Error: This installation supports only FreeBSD 15, but you have FreeBSD $osVer installed."
    exit 201
endif

# Ask, just in case
echo -n "This script will install OpenVK on your FreeBSD machine. It's recommended to run it in FreeBSD Jail via bastille or similar tool. Continue? (y/n)"
set ans = $<

if ( "$ans" != "y" && "$ans" != "Y" && "$ans" != "yes" && "$ans" != "YES") then
    echo "Script aborted by user."
    exit 1
endif

# Install required packages
pkg install -y git nginx php83 node24 npm-node24 php83-composer mod_php83 php83-gd php83-mbstring php83-iconv php83-sodium php83-calendar php83-curl php83-brotli php83-zip php83-ctype php83-dom php83-fileinfo php83-pdo_mysql php83-sqlite3 php83-pdo_sqlite php83-sockets php83-tokenizer php83-opcache php83-posix php83-pecl-yaml php83-phar php83-filter php83-zlib php83-session php83-simplexml php83-pecl-imagick php83-xml

# Install chandler
mkdir /opt
cd /opt
git clone https://github.com/openvk/chandler.git

cd chandler
yes | composer install
chown -R www: .
chmod -R 777 .

# Install CommitCaptcha
cd ./extensions/available
git clone https://github.com/openvk/commitcaptcha.git

cd commitcaptcha
yes | composer install
chown -R www: .
chmod -R 777 .

cd /opt/chandler
ln -s /opt/chandler/extensions/available/commitcaptcha /opt/chandler/extensions/enabled/commitcaptcha

# Install OpenVK
cd ..
git clone https://github.com/openvk/openvk
cd openvk
yes | composer install
# js static
cd Web/static/js
npm i
ln -s /opt/chandler/extensions/available/openvk /opt/chandler/extensions/enabled/openvk

cp /opt/chandler/extensions/available/openvk/install/automated/common/chandler.yml /opt/chandler/chandler.yml
cp /opt/chandler/extensions/available/openvk/install/automated/common/openvk.template.yml /opt/chandler/extensions/available/openvk/openvk.yml

cd ../../../
chown -R www: .
chmod -R 777 .

# Setup databases
sysrc mysql_enable="yes"
service mysql-server start

cd /opt/chandler
mysql < /opt/chandler/extensions/available/openvk/install/automated/common/mk_db.sql
mysql -p'justMonika' openvk < install/init-db.sql
mysql -p'justMonika' openvk < /opt/chandler/extensions/available/openvk/install/init-static-db.sql
mysql -p'justMonika' openvk-eventdb < /opt/chandler/extensions/available/openvk/install/init-event-db.sql

cd /opt/chandler/extensions/available/openvk/install/sqls
foreach migration (*.sql)
    mysql -p'justMonika' openvk < $migration
end

# Change database settings
#echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'justMonika'; FLUSH PRIVILEGES;" | mysql -p'justMonika';

#sed -i'' -e 's:/var/run/mysql/mysql.sock:/tmp/mysql.sock:' /opt/chandler/chandler.yml
#sed -i'' -e 's:/var/run/mysql/mysql.sock:/tmp/mysql.sock:' /opt/chandler/extensions/available/openvk/openvk.yml

# NGINX
sysrc php_fpm_enable="YES"
service php_fpm start

cp /opt/chandler/extensions/available/openvk/install/automated/common/nginx.conf /usr/local/etc/nginx/nginx.conf

sysrc nginx_enable="YES"
service nginx start

# Enjoy
echo "~================ OpenVK is Installed! ================~"
echo "               Use it: http://localhost:80/             "
echo "  Default login: admin@localhost.localdomain6           "
echo "       Password: admin                                  "
echo "~======================================================~"
