#!/bin/tcsh

##########################################################################################################\
#         OpenVK AutoInstallation Script for FreeBSD 15         #               /(        )`               #
# ------------------------------------------------------------- #               \ \___   / |               #
#                                                               #               /- _  `-/  '               #
# This script installs OpenVK on an empty FreeBSD 15 box/jail.  #              (/\/ \ \   /\               #
# Copyright (c) 2026 OpenVK contributors                        #              / /   | `    \              #
# ------------------------------------------------------------- #              O O   ) /    |              #
#                                                               #              `-^--'`<     '              #
# This scropt is free software; you can redistribute it and/or  #             (_.)  _  )   /               #
# modify it under the terms of the GNU Lesser General Public    #              `.___/`    /                #
# License as published by the Free Software Foundation; ver 2.1 #                `-----' /                 #
#                                                               #   <----.     __ / __   \                 #
# This script is distributed in the hope that it will be        #  <----|====O)))==) \) /====|             #
# useful, but WITHOUT ANY WARRANTY; without even the implied    #   <----'    `--' `.__,' \                #
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR       #                |        |                #
# PURPOSE. See the GNU Lesser General Public License for more   #                 \       /       /\       #
# details.                                                      #            ______( (_  / \______/        #
###########################################################################################################/

# Verify compatability
command -v freebsd-version
if ($? == 1) then
    echo "Fatal Error: This installation script is for FreeBSD only."
    exit 200
endif

set osVer = `freebsd-version -r`
if ($osVer !~ "15.*") then
    echo "Fatal Error: This installation supports only FreeBSD 15, but you have FreeBSD $osVer installed."
    exit 201
endif

set ifRoot = `id -c`
if ($ifRoot != "root") then
    echo "Fatal Error: You should run this installation as root."
    exit 202
endif

# Ask, just in case
echo -n "This script will install OpenVK on your FreeBSD machine. It's recommended to run it in FreeBSD Jail via bastille or similar tool. Continue? (y/n)"
set ans = $<

if ( "$ans" != "y" && "$ans" != "Y" && "$ans" != "yes" && "$ans" != "YES") then
    echo "Script aborted by user."
    exit 1
endif

# Install required packages
pkg install -y git nginx php84 node24 npm-node24 mariadb118-server go126 redis php84-composer mod_php84 php84-gd php84-mbstring php84-iconv php84-sodium php84-calendar php84-curl php84-brotli php84-zip php84-ctype php84-dom php84-fileinfo php84-pdo_mysql php84-sqlite3 php84-pdo_sqlite php84-sockets php84-tokenizer php84-opcache php84-posix php84-pecl-yaml php84-phar php84-filter php84-zlib php84-session php84-simplexml php84-xmlreader php84-pecl-imagick php84-xml
rehash # upd exports

mkdir /opt

# Install OpenVK
cd /opt
git clone https://github.com/openvk/openvk
cd openvk
yes | composer install
# js static
cd Web/static/js
npm i

cd /opt
cp openvk/install/automated/common/openvk.template.yml openvk/openvk.yml

chown -R www: /opt/openvk
chmod -R 777 /opt/openvk

# Setup databases
sysrc mysql_enable="yes"
service mysql-server start

# Enable unix sockets in Redis
echo "unixsocket /var/run/redis/redis.sock" >> /usr/local/etc/redis.conf
echo "unixsocketperm 777" >> /usr/local/etc/redis.conf

# Enable redis
sysrc redis_enable="yes"
service redis start

cd /opt/openvk
mysql < install/automated/common/mk_db.sql
mysql -p'justMonika' openvk < vendor/openvk/chandler/install/init-db.sql
mysql -p'justMonika' openvk < install/init-static-db.sql
mysql -p'justMonika' openvk-eventdb < install/init-event-db.sql

cd install/sqls
foreach migration (*.sql)
    mysql -p'justMonika' openvk < $migration
end

# Install OpenVK-IM
cd /opt
git clone https://github.com/openvk/openvk-im
cd openvk-im
cp .env.example .env
sed -i'' -e 's:DB_USER=root:DB_USER=openvk:' /opt/openvk-im/.env
sed -i'' -e 's:DB_PASS=root:DB_PASS=justMonika:' /opt/openvk-im/.env
sed -i'' -e 's:# DB_SOCKET=.*:DB_SOCKET=/var/run/mysql/mysql.sock:' /opt/openvk-im/.env
sed -i'' -e 's:# REDIS_SOCKET=.*:REDIS_SOCKET=/var/run/redis/redis.sock:' /opt/openvk-im/.env
sed -i'' -e 's:APP_PORT=8080:APP_PORT=8420:' /opt/openvk-im/.env
sed -i'' -e 's:SECRET_KEY = "key":SECRET_KEY="'`openssl rand -base64 52 | tr -dc 'A-Za-z0-9' | head -c 64`'":' /opt/openvk-im/.env

go126 mod download
go126 run main.go db create
go126 build -o openvk-im .


cp /opt/openvk/install/automated/freebsd-15/openvk_im /usr/local/etc/rc.d/openvk_im
chmod 755 /usr/local/etc/rc.d/openvk_im
sysrc openvk_im_enable="YES"
service openvk_im start

# NGINX
sysrc php_fpm_enable="YES"
service php_fpm start

cp /opt/openvk/install/automated/common/nginx.conf /usr/local/etc/nginx/nginx.conf

sysrc nginx_enable="YES"
service nginx start

# Enjoy
echo "~================ OpenVK is Installed! ================~"
echo "               Use it: http://localhost:80/             "
echo "  Default login: admin@localhost.localdomain6           "
echo "       Password: admin                                  "
echo "~============= Maintaining instructions ===============~"
echo "  Updating OpenVK:                                      " 
echo "    just run 'git pull --autostash'                     "
echo "    in /opt/openvk directory, then './openvkcli upgrade'"
echo "  Updating OpenVK IM microservice:                      "
echo "    run 'git pull', then 'go126 build -o openvk-im .',  "
echo "    in /opt/openvk-im directory,                        "
echo "    restart service: 'service openvk-im restart'        "
echo "~======================================================~"
