#!/bin/sh

# PROVIDE: openvk_im
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr

name="openvk_im"
rcvar="openvk_im_enable"

service_user="root"
service_dir="/opt/openvk-im"

pidfile="/var/run/${name}.pid"
command="/usr/local/bin/go126 run main.go"

load_rc_config $name
run_rc_command "$1"
