apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mariadb-primary-pvc
    namespace: openvk
    annotations: {}
      # volume.beta.kubernetes.io/storage-class: "efs-sc"
  spec:
    # storageClassName: efs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mariadb-eventdb-pvc
    namespace: openvk
    annotations: {}
      # volume.beta.kubernetes.io/storage-class: "efs-sc"
  spec:
    # storageClassName: efs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: openvk
    namespace: openvk
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: openvk
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: openvk
      spec:
        containers:
        - env: []
          image: ghcr.io/openvk/openvk/openvk:latest
          imagePullPolicy: Always
          name: openvk
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/log/openvk
            name: openvk-logs
          - mountPath: /opt/chandler/extensions/available/openvk/openvk.yml
            name: openvk-config
            subPath: openvk.yml
          - mountPath: /opt/chandler/chandler.yml
            name: openvk-config
            subPath: chandler.yml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: openvk-logs
          emptyDir: {}
        - name: openvk-config
          configMap:
            name: openvk-config
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mariadb-primary
    namespace: openvk
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mariadb-primary
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mariadb-primary
      spec:
        containers:
        - env:
          - name: MARIADB_DATABASE
            value: "db"
          - name: MARIADB_USER
            value: "openvk"
          - name: MARIADB_PASSWORD
            value: "openvk"
          - name: MARIADB_RANDOM_ROOT_PASSWORD
            value: "yes"
          image: ghcr.io/openvk/openvk/mariadb:10.9-primary
          imagePullPolicy: Always
          name: mariadb-primary
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-primary
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: mariadb-primary
          persistentVolumeClaim:
            claimName: mariadb-primary-pvc
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mariadb-eventdb
    namespace: openvk
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mariadb-eventdb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mariadb-eventdb
      spec:
        containers:
        - env:
          - name: MARIADB_DATABASE
            value: "openvk_eventdb"
          - name: MARIADB_USER
            value: "openvk"
          - name: MARIADB_PASSWORD
            value: "openvk"
          - name: MARIADB_RANDOM_ROOT_PASSWORD
            value: "yes"
          image: ghcr.io/openvk/openvk/mariadb:10.9-eventdb
          imagePullPolicy: Always
          name: mariadb-eventdb
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-eventdb
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: mariadb-eventdb
          persistentVolumeClaim:
            claimName: mariadb-eventdb-pvc
- apiVersion: v1
  kind: Service
  metadata:
    name: mariadb-primary-svc
    namespace: openvk
  spec:
    ports:
    - name: mysql
      port: 3306
    selector:
      app: mariadb-primary
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: mariadb-eventdb-svc
    namespace: openvk
  spec:
    ports:
    - name: mysql
      port: 3306
    selector:
      app: mariadb-eventdb
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: openvk-svc
    namespace: openvk
  spec:
    ports:
    - name: http
      port: 80
    selector:
      app: openvk
    type: LoadBalancer
kind: List
metadata: {}