name: Static analysis

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    
    # 'push' runs on inner branches, 'pull_request' will run only on outer PRs
    if: >
      github.event_name == 'push'
      || (github.event_name == 'pull_request'
          && github.event.pull_request.head.repo.full_name != github.repository)

    permissions:
      contents: read
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: gd, zip, intl, yaml, pdo_mysql, rdkafka, imagick
          tools: composer:v2
          coverage: none

      - name: Checkout Chandler
        uses: actions/checkout@v4
        with:
          repository: openvk/chandler

      - name: Install Chandler dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Checkout OpenVK
        uses: actions/checkout@v4
        with:
          path: extensions/available/openvk

      - name: Install OpenVK dependencies
        working-directory: extensions/available/openvk
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: PHPStan
        working-directory: extensions/available/openvk
        run: composer run-script analyse
